version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: view_component
    versions:
    - 2.26.0
    - 2.28.0
    - 2.31.0
    - 2.31.1
  - dependency-name: activemodel
    versions:
    - 6.1.3.1
  - dependency-name: rspec-rails
    versions:
    - 5.0.1
  - dependency-name: rails
    versions:
    - 6.1.2
    - 6.1.2.1
  - dependency-name: activerecord
    versions:
    - 6.1.2.1
