require 'pry'
require 'view_component/test_helpers'
require 'simplecov'

require File.expand_path("dummy/config/environment", __dir__)

if ENV.fetch('SIMPLECOV') { '1' } == '1'
  SimpleCov.add_filter('spec/dummy')
  SimpleCov.start
end

Dir[File.join('./spec', 'components', 'shared', '*.rb')].sort.each { |file| require file }

# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# The generated `.rspec` file contains `--require spec_helper` which will cause
# this file to always be loaded, without a need to explicitly require it in any
# files.
#
# Given that it is always loaded, you are encouraged to keep this file as
# light-weight as possible. Requiring heavyweight dependencies from this file
# will add to the boot time of your test suite on EVERY test run, even for an
# individual file that may not need all of that loaded. Instead, consider making
# a separate helper file that requires the additional dependencies and performs
# the additional setup, and require it from the spec files that actually need
# it.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
RSpec.configure do |config|
  # Allow ViewComponents to be tested
  config.include ViewComponent::TestHelpers, type: :component
  config.include RSpecHtmlMatchers

end
